In [13]:
import pandas as pd
from jqdatasdk import *
from pypfopt import risk_models
from pyfinance import ols
import os
auth("16605926749",".......")
os.chdir('/Users/zifuyi/Desktop/covariance')

In [4]:
stocks = get_index_stocks('000016.XSHG')
start_date="2015-01-01"
end_date="2019-08-31"

In [ ]:
price_data=get_price(stocks, start_date=start_date, end_date=end_date, 
                     frequency='daily', fields=["close"], skip_paused=False, 
                     fq='pre', count=None)
price_data=price_data["close"]
price_data.to_csv("price_data.csv")
price_data.head().append(price_data.tail())

In [5]:
price_data=pd.read_csv("price_data.csv",index_col=0)
price_data.head().append(price_data.tail())

,600000.XSHG,600016.XSHG,600019.XSHG,600028.XSHG,600029.XSHG,600030.XSHG,600031.XSHG,600036.XSHG,600048.XSHG,600050.XSHG,...,601766.XSHG,601800.XSHG,601818.XSHG,601857.XSHG,601888.XSHG,601939.XSHG,601988.XSHG,601989.XSHG,603259.XSHG,603993.XSHG
2015-01-05,9.84,7.66,6.17,5.62,5.33,31.29,9.58,14.08,10.17,5.07,...,6.44,12.48,4.05,11.13,22.04,5.48,3.49,9.35,NaN,3.01
2015-01-06,9.88,7.40,5.93,5.51,5.43,31.33,9.31,13.86,9.75,4.98,...,7.08,12.26,3.97,10.94,23.50,5.40,3.60,9.58,NaN,3.10
2015-01-07,9.68,7.47,5.83,5.65,5.49,32.63,9.40,13.64,9.75,5.16,...,7.79,12.98,3.91,11.59,22.73,5.25,3.58,9.50,NaN,3.20
2015-01-08,9.34,7.25,5.61,5.39,5.23,31.82,8.96,13.14,9.29,4.85,...,8.57,12.25,3.74,11.43,21.70,5.03,3.42,9.09,NaN,3.12
2015-01-09,9.45,7.30,5.48,5.30,5.23,31.56,8.79,13.26,9.12,4.80,...,9.42,13.06,3.78,11.29,21.65,5.07,3.53,8.80,NaN,3.09
2019-08-26,11.30,5.78,5.85,4.97,6.64,22.22,13.78,35.00,14.44,5.97,...,7.22,9.97,3.67,6.07,94.84,6.93,3.52,5.86,82.09,3.60
2019-08-27,11.30,5.82,5.95,4.99,6.82,22.77,13.83,34.75,14.37,6.04,...,7.36,10.17,3.67,6.10,95.57,6.95,3.57,5.92,83.32,3.67
2019-08-28,11.32,5.83,5.89,4.98,6.63,22.42,13.56,34.50,14.25,5.93,...,7.33,10.07,3.69,6.09,94.89,6.95,3.54,5.97,83.27,3.61
2019-08-29,11.23,5.83,5.86,4.99,6.62,22.25,13.46,33.93,13.71,5.95,...,7.35,9.98,3.75,6.09,94.90,6.94,3.53,5.96,82.75,3.58
2019-08-30,11.28,5.81,5.81,4.98,6.57,22.32,13.47,34.28,13.45,5.85,...,7.28,9.98,3.76,6.12,95.48,6.90,3.53,6.08,86.70,3.59

## 1. sample covariance

In [ ]:
cov_data=risk_models.sample_cov(price_data, frequency=252)#frequency=252是一年内交易天数，用来计算年化方差协方差矩阵

## 2. semicovariance

In [ ]:
#benchmark (float) – the benchmark return, defaults to the daily risk-free rate, 
#i.e 1.02(1/252)−1
cov_data=risk_models.semicovariance(price_data,benchmark=7.9e-05, frequency=252)
cov_data

## 3. exponentially weighted covariance

Specify decay in terms of span, 𝛼=2/(𝑠𝑝𝑎𝑛+1), for 𝑠𝑝𝑎𝑛≥1

α[p_0+(1−α)p_1+(1−α)^2*p_2+…+(1−α)^n*p_n+…]

1/α=1+(1−α)+(1−α)2+…

In [ ]:
cov_data=risk_models.exp_cov(price_data, span=180, frequency=252)
cov_data

## 4. mininum covariance determinant
The minimum covariance determinant (MCD) estimator is designed to be robust to *outliers* and ‘contaminated’ data.

In [ ]:
cov_data=risk_models.min_cov_determinant(price_data, frequency=252, random_state=None)
cov_data

## 5. Shrinkage estimators
The essential idea is that the unbiased but often poorly estimated sample covariance can be combined with a structured estimator 𝐹
, using the below formula (where 𝛿 is the shrinkage constant):
 
                                    Σ̂=𝛿𝐹+(1−𝛿)𝑆
It is called shrinkage because it can be thought of as “shrinking” the sample covariance matrix towards the other estimator, which is accordingly called the shrinkage target. The shrinkage target may be significantly biased but has little esimation error. There are many possible options for the target, and each one will result in a different optimal shrinkage constant 𝛿. PyPortfolioOpt offers the following shrinkage methods:
* Ledoit-Wolf shrinkage:
    * constant_variance shrinkage, i.e the target is the diagonal matrix with the mean of asset variances on the diagonals and zeroes elsewhere. 
    * single_factor, Based on Sharpe’s single-index model which effectively uses a stock’s beta to the market as a risk model. 
    * constant_correlation shrinkage, in which all pairwise correlations are set to the average correlation (sample variances are unchanged).

In [ ]:
model=risk_models.CovarianceShrinkage(price_data)
cov_data=model.ledoit_wolf(shrinkage_target='constant_correlation')
cov_data

* Oracle approximating shrinkage (OAS), invented by Chen et al. (2010) [7], which has a lower mean-squared error than Ledoit-Wolf shrinkage when samples are Gaussian or near-Gaussian.

In [ ]:
model=risk_models.CovarianceShrinkage(price_data)
cov_data=model.oracle_approximating()
cov_data

## 滚动回归函数

In [6]:
mkt=get_price("000016.XSHG", start_date=start_date, end_date=end_date, 
                     frequency='daily', fields=["close"], skip_paused=False, 
                     fq='pre', count=None)
mkt=mkt[["close"]]
mkt.head()

              close
2015-01-05  2649.64
2015-01-06  2629.40
2015-01-07  2635.23
2015-01-08  2558.11
2015-01-09  2569.02

In [7]:
mkt=mkt.pct_change()
price_data=price_data.pct_change()
price_data.head()

,600000.XSHG,600016.XSHG,600019.XSHG,600028.XSHG,600029.XSHG,600030.XSHG,600031.XSHG,600036.XSHG,600048.XSHG,600050.XSHG,...,601766.XSHG,601800.XSHG,601818.XSHG,601857.XSHG,601888.XSHG,601939.XSHG,601988.XSHG,601989.XSHG,603259.XSHG,603993.XSHG
2015-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-06,0.004065,-0.033943,-0.038898,-0.019573,0.018762,0.001278,-0.028184,-0.015625,-0.041298,-0.017751,...,0.099379,-0.017628,-0.019753,-0.017071,0.066243,-0.014599,0.031519,0.024599,NaN,0.029900
2015-01-07,-0.020243,0.009459,-0.016863,0.025408,0.011050,0.041494,0.009667,-0.015873,0.000000,0.036145,...,0.100282,0.058728,-0.015113,0.059415,-0.032766,-0.027778,-0.005556,-0.008351,NaN,0.032258
2015-01-08,-0.035124,-0.029451,-0.037736,-0.046018,-0.047359,-0.024824,-0.046809,-0.036657,-0.047179,-0.060078,...,0.100128,-0.056240,-0.043478,-0.013805,-0.045315,-0.041905,-0.044693,-0.043158,NaN,-0.025000
2015-01-09,0.011777,0.006897,-0.023173,-0.016698,0.000000,-0.008171,-0.018973,0.009132,-0.018299,-0.010309,...,0.099183,0.066122,0.010695,-0.012248,-0.002304,0.007952,0.032164,-0.031903,NaN,-0.009615

In [9]:
rolling = ols.PandasRollingOLS(y=price_data["600000.XSHG"], x=mkt["close"], window=250)

/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:153: RuntimeWarning: invalid value encountered in reduce
  umr_maximum(a, axis, None, out, keepdims),
/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in reduce
  umr_minimum(a, axis, None, None, keepdims),

In [10]:
rolling.alpha

2016-01-11         NaN
2016-01-12    0.001298
2016-01-13    0.001283
2016-01-14    0.001452
2016-01-15    0.001516
2016-01-18    0.001507
2016-01-19    0.001454
2016-01-20    0.001385
2016-01-21    0.001236
2016-01-22    0.001277
2016-01-25    0.001207
2016-01-26    0.001390
2016-01-27    0.001334
2016-01-28    0.001368
2016-01-29    0.001372
2016-02-01    0.001361
2016-02-02    0.001419
2016-02-03    0.001472
2016-02-04    0.001609
2016-02-05    0.001917
2016-02-15    0.001900
2016-02-16    0.001831
2016-02-17    0.001794
2016-02-18    0.001834
2016-02-19    0.001811
2016-02-22    0.001722
2016-02-23    0.001798
2016-02-24    0.001750
2016-02-25    0.001932
2016-02-26    0.001914
                ...
2019-07-22    0.000476
2019-07-23    0.000455
2019-07-24    0.000457
2019-07-25    0.000525
2019-07-26    0.000476
2019-07-29    0.000443
2019-07-30    0.000414
2019-07-31    0.000411
2019-08-01    0.000363
2019-08-02    0.000369
2019-08-05    0.000345
2019-08-06    0.000305
2019-08-07    0.000293
2019-08-08    0.000284
2019-08-09    0.000328
2019-08-12    0.000331
2019-08-13    0.000319
2019-08-14    0.000237
2019-08-15    0.000187
2019-08-16    0.000160
2019-08-19    0.000144
2019-08-20    0.000178
2019-08-21    0.000222
2019-08-22    0.000227
2019-08-23    0.000195
2019-08-26    0.000138
2019-08-27    0.000041
2019-08-28    0.000063
2019-08-29    0.000024
2019-08-30    0.000087
Name: intercept, Length: 889, dtype: float64

In [11]:
rolling.beta

            feature1
2016-01-11       NaN
2016-01-12  0.832325
2016-01-13  0.832351
2016-01-14  0.834230
2016-01-15  0.831406
2016-01-18  0.831203
2016-01-19  0.827297
2016-01-20  0.829100
2016-01-21  0.831535
2016-01-22  0.831092
2016-01-25  0.830316
2016-01-26  0.807921
2016-01-27  0.808086
2016-01-28  0.806436
2016-01-29  0.804904
2016-02-01  0.806517
2016-02-02  0.806641
2016-02-03  0.805240
2016-02-04  0.807278
2016-02-05  0.804580
2016-02-15  0.805289
2016-02-16  0.799894
2016-02-17  0.799132
2016-02-18  0.798272
2016-02-19  0.798642
2016-02-22  0.795229
2016-02-23  0.795968
2016-02-24  0.795162
2016-02-25  0.781956
2016-02-26  0.781141
...              ...
2019-07-22  0.757961
2019-07-23  0.756004
2019-07-24  0.756235
2019-07-25  0.758908
2019-07-26  0.760085
2019-07-29  0.760831
2019-07-30  0.760476
2019-07-31  0.753219
2019-08-01  0.755595
2019-08-02  0.757949
2019-08-05  0.760250
2019-08-06  0.762225
2019-08-07  0.762303
2019-08-08  0.762913
2019-08-09  0.761431
2019-08-12  0.754389
2019-08-13  0.755405
2019-08-14  0.757570
2019-08-15  0.758159
2019-08-16  0.759052
2019-08-19  0.759996
2019-08-20  0.764313
2019-08-21  0.763898
2019-08-22  0.763478
2019-08-23  0.765241
2019-08-26  0.770385
2019-08-27  0.770234
2019-08-28  0.769604
2019-08-29  0.768680
2019-08-30  0.774297

[889 rows x 1 columns]